name: nanogpt
channels:
  - pytorch
  - nvidia
  - huggingface
  - conda-forge
  - anaconda
  - defaults
dependencies:
  - python=3.11.9
  - pip=24.2
  - jupyter=1.0.0
  - jupyterlab=4.2.5
  - notebook=7.2.2
  - ipywidgets=8.1.5
  - pandas=2.2.3
  - numpy=2.1.2
  - scipy=1.14.1
  - matplotlib=3.9.2
  - seaborn=0.13.2
  - nltk=3.9.1
  - pytorch=2.5.0
  - torchvision=0.20.0
  - torchaudio=2.5.0
  - pytorch-cuda=12.4.0
  - scikit-learn=1.5.2
  - accelerate=1.0.1
  - transformers=4.45.2
  - datasets=3.0.1
  - pyarrow=17.0.0
  - pip:
      - python-dotenv==1.0.1
      - wandb==0.18.5
      - emoji==2.14.0
      - PyArabic==0.6.15
      - tabulate==0.9.0
      - rich[jupyter]==13.9.2
      - tqdm==4.66.5
