name: nanogpt
channels:
  - pytorch
  - nvidia
  - huggingface
  - conda-forge
  - anaconda
  - defaults
dependencies:
  - python=3.11.9
  - jupyter=1.0.0
  - jupyterlab=4.2.5
  - notebook=7.2.2
  - ipywidgets=8.1.5
  - pandas=2.2.2
  - numpy=1.26.4
  - scipy=1.13.1
  - matplotlib=3.9.2
  - seaborn=0.13.2
  - nltk=3.8.1
  - pytorch=2.4.0
  - torchvision=0.19.0
  - torchaudio=2.4.0
  - pytorch-cuda=12.4.0
  - scikit-learn=1.5.1
  - accelerate=0.34.0
  - transformers=4.44.2
  - datasets=3.0.1
  - pyarrow=17.0.0
  - pip:
      - python-dotenv==1.0.1
      - wandb==0.17.8
      - emoji==2.14.0
      - PyArabic==0.6.15
      - tabulate==0.9.0
      - rich[jupyter]==13.8.0
      - tqdm==4.66.5
